# Generated by Django 4.2.7 on 2025-05-01 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Payment Pending'), ('rejected', 'Rejected'), ('paid', 'Payment Received'), ('in_progress', 'In Progress'), ('assembling', 'Assembly in Progress'), ('testing', 'Testing'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('service_charge', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('assembly_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_custom_builds', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_pc_case', to='products.product')),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_pc_cpu', to='products.product')),
                ('gpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_pc_gpu', to='products.product')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_pc_motherboard', to='products.product')),
                ('power_supply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_pc_power_supply', to='products.product')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_pc_ram', to='products.product')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shippingaddress')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_pc_storage', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
